/**
 * Curated list of ~150 common technical and soft skills for resume parsing and matching
 */

const KNOWN_SKILLS = [
  // ── Programming Languages (25) ──
  { name: 'JavaScript', category: 'technical' },
  { name: 'TypeScript', category: 'technical' },
  { name: 'Python', category: 'technical' },
  { name: 'Java', category: 'technical' },
  { name: 'C++', category: 'technical' },
  { name: 'C#', category: 'technical' },
  { name: 'C', category: 'technical' },
  { name: 'Go', category: 'technical' },
  { name: 'Rust', category: 'technical' },
  { name: 'Ruby', category: 'technical' },
  { name: 'PHP', category: 'technical' },
  { name: 'Swift', category: 'technical' },
  { name: 'Kotlin', category: 'technical' },
  { name: 'SQL', category: 'technical' },
  { name: 'HTML5', category: 'technical' },
  { name: 'CSS3', category: 'technical' },
  { name: 'HTML', category: 'technical' },
  { name: 'CSS', category: 'technical' },
  { name: 'Dart', category: 'technical' },
  { name: 'R', category: 'technical' },
  { name: 'Scala', category: 'technical' },
  { name: 'Shell', category: 'technical' },
  { name: 'Bash', category: 'technical' },
  { name: 'Solidity', category: 'technical' },
  { name: 'MATLAB', category: 'technical' },

  // ── Frontend Frameworks & Libraries (18) ──
  { name: 'React', category: 'technical' },
  { name: 'Next.js', category: 'technical' },
  { name: 'Vue.js', category: 'technical' },
  { name: 'Angular', category: 'technical' },
  { name: 'Svelte', category: 'technical' },
  { name: 'Tailwind CSS', category: 'technical' },
  { name: 'TailwindCSS', category: 'technical' },
  { name: 'Bootstrap', category: 'technical' },
  { name: 'Redux', category: 'technical' },
  { name: 'Zustand', category: 'technical' },
  { name: 'Vite', category: 'technical' },
  { name: 'Webpack', category: 'technical' },
  { name: 'Framer Motion', category: 'technical' },
  { name: 'Three.js', category: 'technical' },
  { name: 'Sass', category: 'technical' },
  { name: 'jQuery', category: 'technical' },
  { name: 'shadcn/ui', category: 'technical' },
  { name: 'Responsive Design', category: 'technical' },

  // ── Backend & API Frameworks (20) ──
  { name: 'Node.js', category: 'technical' },
  { name: 'Express.js', category: 'technical' },
  { name: 'Express', category: 'technical' },
  { name: 'Django', category: 'technical' },
  { name: 'Flask', category: 'technical' },
  { name: 'FastAPI', category: 'technical' },
  { name: 'Spring Boot', category: 'technical' },
  { name: 'Spring', category: 'technical' },
  { name: 'ASP.NET', category: 'technical' },
  { name: 'NestJS', category: 'technical' },
  { name: 'Ruby on Rails', category: 'technical' },
  { name: 'Laravel', category: 'technical' },
  { name: 'GraphQL', category: 'technical' },
  { name: 'REST API', category: 'technical' },
  { name: 'RESTful APIs', category: 'technical' },
  { name: 'gRPC', category: 'technical' },
  { name: 'Microservices', category: 'technical' },
  { name: 'Socket.io', category: 'technical' },
  { name: 'WebSockets', category: 'technical' },
  { name: 'Kafka', category: 'technical' },

  // ── Databases & Storage (16) ──
  { name: 'PostgreSQL', category: 'technical' },
  { name: 'MongoDB', category: 'technical' },
  { name: 'MySQL', category: 'technical' },
  { name: 'Redis', category: 'technical' },
  { name: 'SQLite', category: 'technical' },
  { name: 'Firebase', category: 'technical' },
  { name: 'Firestore', category: 'technical' },
  { name: 'Supabase', category: 'technical' },
  { name: 'Cassandra', category: 'technical' },
  { name: 'DynamoDB', category: 'technical' },
  { name: 'Elasticsearch', category: 'technical' },
  { name: 'Oracle DB', category: 'technical' },
  { name: 'Prisma', category: 'technical' },
  { name: 'Mongoose', category: 'technical' },
  { name: 'Database Design', category: 'technical' },
  { name: 'Data Modeling', category: 'technical' },

  // ── Cloud, DevOps & Infrastructure (18) ──
  { name: 'AWS', category: 'technical' },
  { name: 'Azure', category: 'technical' },
  { name: 'GCP', category: 'technical' },
  { name: 'Google Cloud', category: 'technical' },
  { name: 'Docker', category: 'technical' },
  { name: 'Kubernetes', category: 'technical' },
  { name: 'CI/CD', category: 'technical' },
  { name: 'GitHub Actions', category: 'technical' },
  { name: 'Jenkins', category: 'technical' },
  { name: 'Terraform', category: 'technical' },
  { name: 'Linux', category: 'technical' },
  { name: 'Nginx', category: 'technical' },
  { name: 'Git', category: 'technical' },
  { name: 'GitHub', category: 'technical' },
  { name: 'GitLab', category: 'technical' },
  { name: 'Serverless', category: 'technical' },
  { name: 'Ansible', category: 'technical' },
  { name: 'Cloud Computing', category: 'technical' },

  // ── AI, Data Science & Machine Learning (18) ──
  { name: 'Machine Learning', category: 'technical' },
  { name: 'Deep Learning', category: 'technical' },
  { name: 'Artificial Intelligence', category: 'technical' },
  { name: 'Data Science', category: 'technical' },
  { name: 'Data Analysis', category: 'technical' },
  { name: 'Natural Language Processing', category: 'technical' },
  { name: 'NLP', category: 'technical' },
  { name: 'Computer Vision', category: 'technical' },
  { name: 'PyTorch', category: 'technical' },
  { name: 'TensorFlow', category: 'technical' },
  { name: 'Scikit-learn', category: 'technical' },
  { name: 'Pandas', category: 'technical' },
  { name: 'NumPy', category: 'technical' },
  { name: 'OpenCV', category: 'technical' },
  { name: 'Large Language Models', category: 'technical' },
  { name: 'Prompt Engineering', category: 'technical' },
  { name: 'LangChain', category: 'technical' },
  { name: 'Hugging Face', category: 'technical' },

  // ── Web3, Testing, Tools & Design (15) ──
  { name: 'Ethers.js', category: 'technical' },
  { name: 'Web3.js', category: 'technical' },
  { name: 'Hardhat', category: 'technical' },
  { name: 'Smart Contracts', category: 'technical' },
  { name: 'Blockchain', category: 'technical' },
  { name: 'Jest', category: 'technical' },
  { name: 'Vitest', category: 'technical' },
  { name: 'Cypress', category: 'technical' },
  { name: 'Postman', category: 'technical' },
  { name: 'Figma', category: 'technical' },
  { name: 'UI/UX Design', category: 'technical' },
  { name: 'Cybersecurity', category: 'technical' },
  { name: 'Penetration Testing', category: 'technical' },
  { name: 'Cryptography', category: 'technical' },
  { name: 'Unit Testing', category: 'technical' },

  // ── Soft Skills & Professional Attributes (26) ──
  { name: 'Problem Solving', category: 'soft' },
  { name: 'Critical Thinking', category: 'soft' },
  { name: 'Communication', category: 'soft' },
  { name: 'Teamwork', category: 'soft' },
  { name: 'Leadership', category: 'soft' },
  { name: 'Time Management', category: 'soft' },
  { name: 'Adaptability', category: 'soft' },
  { name: 'Collaboration', category: 'soft' },
  { name: 'Project Management', category: 'soft' },
  { name: 'Agile', category: 'soft' },
  { name: 'Scrum', category: 'soft' },
  { name: 'Public Speaking', category: 'soft' },
  { name: 'Conflict Resolution', category: 'soft' },
  { name: 'Decision Making', category: 'soft' },
  { name: 'Analytical Thinking', category: 'soft' },
  { name: 'Presentation Skills', category: 'soft' },
  { name: 'Emotional Intelligence', category: 'soft' },
  { name: 'Negotiation', category: 'soft' },
  { name: 'Mentoring', category: 'soft' },
  { name: 'Creativity', category: 'soft' },
  { name: 'Work Ethic', category: 'soft' },
  { name: 'Attention to Detail', category: 'soft' },
  { name: 'Self-Motivation', category: 'soft' },
  { name: 'Active Listening', category: 'soft' },
  { name: 'Strategic Thinking', category: 'soft' },
  { name: 'Interpersonal Skills', category: 'soft' },
];

module.exports = {
  KNOWN_SKILLS,
};
